project_name: talklistener
release:
  github:
    owner: but80
    name: talklistener
brew:
  github:
    owner: but80
    name: homebrew-tap
builds:
  - id: talklistener
    goos:
      - linux
      - darwin
      # - windows
    goarch:
      - amd64
    ignore:
      - goos: linux
        goarch: 386
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: 386
    main: ./main.go
    ldflags: -s -w -X main.version={{.Version}}
    binary: talklistener
    hooks:
      pre: GO111MODULE=on go run -mod=vendor mage.go cmodules
before:
  hooks:
    - GO111MODULE=on go run -mod=vendor mage.go cmodules
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  name_template: '{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}'
  files:
    - LICENSE*
    - CREDITS*
    - README*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^Update README'
